#!/usr/bin/env python3
"""Emit assets/font5x7.h from the glyph table in font5x7.py."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import font5x7 as F

data = F.table()
out = sys.argv[1] if len(sys.argv) > 1 else "assets/font5x7.h"
L = ["/* Generated by tools/font2c.py - do not edit by hand. */",
     "#ifndef ASSET_FONT5X7_H", "#define ASSET_FONT5X7_H", "",
     "#define FONT_FIRST_CHAR %d" % F.FIRST,
     "#define FONT_LAST_CHAR  %d" % F.LAST,
     "#define FONT_GLYPH_W    %d" % F.GLYPH_W,
     "#define FONT_GLYPH_H    %d" % F.GLYPH_H,
     "#define FONT_CELL_W     %d" % F.CELL_W,
     "#define FONT_CELL_H     %d" % F.CELL_H, "",
     "/* One byte per glyph row, bit 7 = leftmost column. */",
     "static const unsigned char font5x7_bits[%d] = {" % len(data)]
for i in range(0, len(data), F.GLYPH_H):
    L.append("    " + ",".join("0x%02X" % b for b in data[i:i + F.GLYPH_H]) +
             ",  /* '%s' */" % (chr(F.FIRST + i // F.GLYPH_H).replace("\\", "\\\\")))
L += ["};", "", "#endif /* ASSET_FONT5X7_H */"]
open(out, "w").write("\n".join(L) + "\n")
print("font5x7        %d glyphs, %d bytes" % (len(data)//F.GLYPH_H, len(data)), file=sys.stderr)
